# Generated by Django 3.2.12 on 2022-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Загаловок')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/', verbose_name='Фото')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
            ],
            options={
                'verbose_name': 'Главная Категория',
                'verbose_name_plural': 'Категории Ивентов',
            },
        ),
    ]
