# Generated by Django 3.2.12 on 2022-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Электронный адресс')),
                ('description', models.TextField(null=True, verbose_name='Вопрос или пожeлание')),
                ('data_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Обратный звонок и вопрос',
                'verbose_name_plural': 'Обратные звонки и вопросы',
            },
        ),
    ]
