# Generated by Django 3.2.12 on 2022-04-05 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Нумерация')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Сотовый телефон')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_admin', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_events', to='events.events', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
