# Generated by Django 3.2.12 on 2022-04-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestslist',
            name='number_secand',
        ),
    ]
