# Generated by Django 3.2.12 on 2022-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestslist',
            name='numeration',
        ),
        migrations.AlterField(
            model_name='guestslist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Сотовый телефон'),
        ),
    ]
