# Generated by Django 3.2.12 on 2022-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20220407_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileUploud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_uploud', models.FileField(upload_to='excel')),
            ],
        ),
    ]
