# Generated by Django 3.2.12 on 2022-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guestslist_number_secand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestslist',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Полное имя'),
        ),
    ]
