# Generated by Django 3.2.12 on 2022-04-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0002_auto_20220416_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestslist',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='guests_admin', to='guests.guestsadmin', verbose_name='Админ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestslist',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
