# Generated by Django 3.2.12 on 2022-04-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20220421_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestslist',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_admin', to='guests.guestsadmin', verbose_name='Админ'),
        ),
    ]
