# Generated by Django 3.2.12 on 2022-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_guestslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestslist',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Статус'),
        ),
    ]
